name: Compile ESP8266 GMpro87

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266 Platform (SDK 2.0.0)
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          # Menginstall versi 2.0.0 secara spesifik
          arduino-cli core install esp8266:esp8266@2.0.0

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 Sketch/Sketch.ino
